name: main

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar o JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compilar o código
      run: javac -d target/classes -cp .:lib/junit-4.13.2.jar Codigo/src/br/calebe/ticketmachine/core/TicketMachine.java

    - name: Compilar os testes
      run: javac -d target/test-classes -cp .:lib/junit-4.13.2.jar Codigo/src/Test/Codigo/TicketMachineTest.java

    - name: Executar testes JUnit
      run: java -cp .:lib/junit-4.13.2.jar:target/classes:target/test-classes org.junit.runner.JUnitCore Test.Codigo.TicketMachineTest

  
   
