name: main

on:
  push:
    branches:
      - master  # Substitua "main" pelo nome da sua branch principal, se necessário

jobs:
  build:
    runs-on: ubuntu-latest  # Você pode escolher outro sistema operacional, se preferir

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Configurar o JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Debug Info
      run: |
        ls -la
        pwd
        echo $GITHUB_WORKSPACE
    - name: Sair do diretório e voltar para a raiz
      run: cd ..
    - name: Compilar o arquivo Java
      run: javac "Codigo/src/br/calebe/ticketmachine/core/TicketMachine.java"  # Substitua "SeuArquivo.java" pelo nome do seu arquivo Java

    - name: Enviar artefatos
      run: |
        mkdir -p compiled
        mv *.class compiled/
      continue-on-error: true

    - name: Enviar artefatos para o GitHub
      uses: actions/upload-artifact@v2
      with:
        name: java-compiled
        path: compiled

    - name: Copy JUnit JAR to the workspace
      run: cp "lib/junit-4.13.2.jar" .

    - name: Debug Info2
      run: |
        ls -la
        pwd
        echo $GITHUB_WORKSPACE
        
    - name: Compile
      working-directory: ./Codigo
      run: javac -cp .:lib/junit-4.13.2.jar "Test/TicketMachineTest.java"

    - name: Run Unit Tests
      run: java -cp .:lib/junit-4.13.2.jar org.junit.runner.JUnitCore TicketMachineTest

  
